### ISSUE TITLE
forgotten breakpoint

### ISSUE THREAD

**Issue by jankvapil** [ULL-ESIT-PL/moo-ignore#2]
https://github.com/ULL-ESIT-PL/moo-ignore/blob/8116c356ace194faa9b38ffe79ec6668328c8503/index.js#L60

**Comment by jankvapil** [comment]
@crguezl  Can you please remove this debugger symbol? It's impossible to use this library in browser because of this

**Comment by crguezl** [comment]
Thanks for the comment. Done although with the phone 📞
